# Generated by Django 5.0.2 on 2024-04-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('fecha_nacimiento', models.DateField(default=False, verbose_name='Fecha de nacimiento')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Personas.documento')),
            ],
        ),
    ]
